### ISSUE TITLE
Repository has wrong directory structure

### ISSUE THREAD

**Issue by jbrucker** [PanidaOun/ku-polls#11]
Your git repository has:
```
# ku-polls repository
.gitignore
mysite/
          mysite/
          polls/
          manage.py
```
should be (as stated with example in the assignment!)
```
.gitignore
mysite/
polls/
manage.py
```
You have done this on many assignments.
Please pay better attention to what you are doing.

You could fix this using "git mv ..." for each file/dir,
but be careful.  If you mess up, you can use "git reset" to undo
before committing.

Next time, avoid the extra layer of directories.

**Comment by PanidaOun** [comment]
Apologize , Sorry.
