### ISSUE TITLE
Some issues in requirements

### ISSUE THREAD

**Issue by MaiNorapong** [PanidaOun/ku-polls#2]
### Requirements

> 3.&nbsp;User can edit a previous submission.
> 4.&nbsp;User can modify their choice any time during the polling period.

> 7.&nbsp;User can't vote or modify an existing vote after the closing date.

How is editing and modifying different? Do they not refer to the same thing?

A missing capability seems to be the ability to vote. Only the inability to vote after the closing date is in the requirements. Can anyone vote?

### Side Note: English

"user" is a singular noun and needs a *determiner*. This can be many things including an *article* (a/an/the). See more at [Wikipedia](https://en.wikipedia.org/wiki/Determiner). To remedy this, you can change the noun from singular to plural (so that it doesn't need a determiner) or add an article in front.

p.s. Once you've fixed the issue, you can reply to this thread. GitHub will send an email to the people involved and they will see your reply.

**Comment by PanidaOun** [comment]
fixed.thank you.
